apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp-deploy
    spec:
      containers:
      - name: webapp
        image: webapp
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /self
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15

---

kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app:  webapp-deploy
  type:  NodePort
  ports:
  - 
    port:  80
    targetPort:  80
    nodePort: 30000