version : '3.7'

services:
  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!
    ports:
      - 1433:1433
  redis:
    image: redis
    ports:
      - 6379:6379
